# all commented variable need to be defined here, or passed via Survey or extra vars in Tower

#ansible_connection: ''
#backup_path: ''
ansible_network_os: "{{ ansible_net_system }}"
network_backup_dir: "{{ backup_path }}"
network_backup_file: "{{ network_backup_dir }}/{{ inventory_hostname }}.cfg"
#git_name: ''
#git_email: ''
