---
# These tasks are responsible for copying the latest dev/production code from
# the version control system.

- name: Copy the code from repository
  git: repo={{ repository }} dest=/var/www/html/

- name: Creates the index.php file for webserver Group
  template: src=index.php.j2 dest=/var/www/html/index.php
  when: "'webservers' in group_names"

- name: Creates the index.php file for Type_webserver Group
  template: src=indexazure.php.j2 dest=/var/www/html/index.php
  when: "'Type_webservers' in group_names"

- name: Creates the index.php file for Type_webserver Group
  template: src=indexaws.php.j2 dest=/var/www/html/index.php
  when: "'tag_Type_webservers' in group_names"
